# Generated by Django 5.0.1 on 2024-02-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_alter_menuitem_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="show_on_main",
            field=models.BooleanField(
                default=True, verbose_name="показывать на главной"
            ),
            preserve_default=False,
        ),
    ]
